on: [push, pull_request]

name: CI for 'systemd-socket-activation'

jobs:

  build:
    name: Test the package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: ['8.10', '9.0', '9.2']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Haskell dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '.github/workflows/test.hs') }}
          restore-keys: |
              ${{ runner.os }}-ghc${{ matrix.ghc }}-
              ${{ runner.os }}-

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Test
        run: runhaskell --ghc-arg='-package process' ./.github/workflows/test.hs
        env:
          ghc: ${{ matrix.ghc }}
